export const SHOW_SEARCH_TABLE ='SHOW_SEARCH_TABLE';
export const HIDE_SEARCH_TABLE ='HIDE_SEARCH_TABLE';
export const SELECTED_INVOICE = 'SELECTED_INVOICE';
export const TABLE_DATA="TABLE_DATA";
export const REFRESH="REFRESH";
export const TO_SEARCH="TO_SEARCH";